version: 1
formatters:
  simple:
    format: '%(asctime)s %(levelname)s %(thread)10d --- [%(threadName)15s] %(name)-30s : %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stderr
root:
  level: DEBUG
  handlers: [ console ]
loggers:
    qsoWidget:
        level: DEBUG
        handlers: [console]
        propagate: yes
    __main__:
        level: DEBUG
        handlers: [console]
        propagate: yes