from prometheus_client import Summary, Counter, Gauge

# Message counters
prometheus_pyrogram_messages_caption = Counter('pyrogram_messages_caption', 'Total count of caption messages received')
prometheus_pyrogram_messages = Counter('pyrogram_messages', 'Total count of messages received')
prometheus_pyrogram_messages_document = Counter('pyrogram_messages_document', 'Total count of document messages received')
prometheus_pyrogram_messages_forwards = Counter('pyrogram_messages_forwards', 'Total count of forwards messages received')
prometheus_pyrogram_messages_group_chat_created = Counter('pyrogram_messages_group_chat_created', 'Total count of group chat created messages received')
prometheus_pyrogram_messages_left_chat_members = Counter('pyrogram_messages_left_chat_members', 'Total count of new chat members messages received')
prometheus_pyrogram_messages_location = Counter('pyrogram_messages_location', 'Total count of location messages received')
prometheus_pyrogram_messages_media = Counter('pyrogram_messages_media', 'Total count of media messages received')
prometheus_pyrogram_messages_new_chat_members = Counter('pyrogram_messages_new_chat_members', 'Total count of new chat members messages received')
prometheus_pyrogram_messages_new_chat_photo = Counter('pyrogram_messages_new_chat_photo', 'Total count of new chat photo messages received')
prometheus_pyrogram_messages_new_chat_title = Counter('pyrogram_messages_new_chat_title', 'Total count of new chat title messages received')
prometheus_pyrogram_messages_photo = Counter('pyrogram_messages_photo', 'Total count of photo messages received')
prometheus_pyrogram_messages_pinned_message = Counter('pyrogram_messages_pinned_message', 'Total count of pinned message messages received')
prometheus_pyrogram_messages_poll = Counter('pyrogram_messages_poll', 'Total count of poll messages received')
prometheus_pyrogram_messages_reactions = Counter('pyrogram_messages_reactions', 'Total count of reactions messages received')
prometheus_pyrogram_messages_service = Counter('pyrogram_messages_service', 'Total count of service messages received')
prometheus_pyrogram_messages_sticker = Counter('pyrogram_messages_sticker', 'Total count of sticker messages received')
prometheus_pyrogram_messages_supergroup_chat_created = Counter('pyrogram_messages_supergroup_chat_created', 'Total count of supergroupd chat created messages received')
prometheus_pyrogram_messages_text = Counter('pyrogram_messages_text', 'Total count of text messages received')
prometheus_pyrogram_messages_video_chat_ended = Counter('pyrogram_messages_video_chat_ended', 'Total count of video chat ended messages received')
prometheus_pyrogram_messages_video_chat_started = Counter('pyrogram_messages_video_chat_started', 'Total count of video chat started messages received')
prometheus_pyrogram_messages_video = Counter('pyrogram_messages_video', 'Total count of video messages received')
prometheus_pyrogram_messages_video_note = Counter('pyrogram_messages_video_note', 'Total count of video note messages received')
prometheus_pyrogram_messages_voice = Counter('pyrogram_messages_voice', 'Total count of voice messages received')

# Chat type counts
prometheus_pyrogram_known_bot_chats = Gauge('pyrogram_known_bot_chats', 'Total number of known bot type chats')
prometheus_pyrogram_known_channel_chats = Gauge('pyrogram_known_channel_chats', 'Total number of known channel type chats')
prometheus_pyrogram_known_group_chats = Gauge('pyrogram_known_group_chats', 'Total number of known group type chats')
prometheus_pyrogram_known_private_chats = Gauge('pyrogram_known_private_chats', 'Total number of known private type chats')
prometheus_pyrogram_known_supergroup_chats = Gauge('pyrogram_known_supergroup_chats', 'Total number of known supergroup type chats')
prometheus_pyrogram_known_unknown_chats = Gauge('pyrogram_known_unknown_chats', 'Total number of known unknown type chats')
